# Generated by Django 6.1.1 on 2026-09-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_name_bn', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_certificate', models.FileField(upload_to='admissions/birth-certificates/')),
                ('previous_class', models.CharField(blank=True, max_length=80)),
                ('applying_class', models.CharField(max_length=80)),
                ('student_photo', models.ImageField(upload_to='admissions/photos/')),
                ('student_address', models.TextField()),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(max_length=150)),
                ('father_occupation', models.CharField(max_length=120)),
                ('mother_occupation', models.CharField(blank=True, max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('guardian_address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=80)),
                ('previous_academic_info', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
