# Generated by Django 6.1.1 on 2026-09-06 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_bn', models.CharField(max_length=80)),
                ('account_number', models.CharField(max_length=80)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('payment_type_en', models.CharField(max_length=80)),
                ('payment_type_bn', models.CharField(max_length=80)),
                ('instructions_en', models.TextField()),
                ('instructions_bn', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payer_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], default='bkash', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, upload_to='admissions/payments/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='transaction_id',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('label_en', models.CharField(default='Admission Fee', max_length=120)),
                ('label_bn', models.CharField(default='ভর্তি ফি', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(blank=True, help_text='Leave empty for the default fee shown to all applicants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_fees', to='content.curriculumgrade')),
            ],
            options={
                'ordering': ['grade__order', 'id'],
            },
        ),
    ]
