# Generated by Django 6.1.1 on 2026-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_paymentmethod_admissionapplication_payer_mobile_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admissionapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('transaction_id',), name='unique_admission_transaction_id'),
        ),
    ]
