# Generated by Django 6.1.1 on 2026-09-06 10:00

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_en', models.TextField()),
                ('introduction_bn', models.TextField()),
                ('vision_en', models.TextField()),
                ('vision_bn', models.TextField()),
                ('mission_en', models.TextField()),
                ('mission_bn', models.TextField()),
                ('history_en', models.TextField()),
                ('history_bn', models.TextField()),
                ('quranic_approach_en', models.TextField()),
                ('quranic_approach_bn', models.TextField()),
                ('principal_message_en', models.TextField()),
                ('principal_message_bn', models.TextField()),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_bn', models.CharField(max_length=120)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location_en', models.CharField(max_length=200)),
                ('location_bn', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150)),
                ('title_bn', models.CharField(max_length=150)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=180)),
                ('title_bn', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('activities', 'School activities'), ('events', 'Events'), ('classroom', 'Classroom activities'), ('cultural', 'Cultural programs'), ('sports', 'Sports'), ('islamic', "Islamic/Qur'anic activities"), ('campus', 'Campus photos')], max_length=20)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_en', models.CharField(max_length=250)),
                ('hero_title_bn', models.CharField(max_length=250)),
                ('hero_subtitle_en', models.TextField()),
                ('hero_subtitle_bn', models.TextField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('welcome_en', models.TextField()),
                ('welcome_bn', models.TextField()),
                ('about_preview_en', models.TextField()),
                ('about_preview_bn', models.TextField()),
                ('principal_name_en', models.CharField(max_length=120)),
                ('principal_name_bn', models.CharField(max_length=120)),
                ('principal_title_en', models.CharField(max_length=120)),
                ('principal_title_bn', models.CharField(max_length=120)),
                ('principal_message_en', models.TextField()),
                ('principal_message_bn', models.TextField()),
                ('principal_photo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Home content',
                'verbose_name_plural': 'Home content',
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_bn', models.CharField(max_length=120)),
                ('role_en', models.CharField(max_length=150)),
                ('role_bn', models.CharField(max_length=150)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_bn', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=220)),
                ('title_bn', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('notice', 'Notice'), ('admission', 'Admission notice'), ('holiday', 'Holiday notice'), ('exam', 'Examination notice'), ('update', 'Important update')], max_length=20)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='news/')),
                ('featured_image_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_en', models.CharField(max_length=200)),
                ('school_name_bn', models.CharField(max_length=200)),
                ('tagline_en', models.CharField(blank=True, max_length=300)),
                ('tagline_bn', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_url', models.URLField(blank=True)),
                ('address_en', models.CharField(max_length=400)),
                ('address_bn', models.CharField(max_length=400)),
                ('phone_primary', models.CharField(max_length=40)),
                ('phone_secondary', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_url', models.URLField(blank=True, max_length=800)),
                ('office_hours_en', models.CharField(max_length=200)),
                ('office_hours_bn', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('admission_open', models.BooleanField(default=True)),
                ('admission_announcement_en', models.TextField(blank=True)),
                ('admission_announcement_bn', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150)),
                ('title_bn', models.CharField(max_length=150)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField()),
                ('icon', models.CharField(default='book', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='curriculum/')),
                ('file_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='content.curriculumgrade')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('caption_bn', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.galleryalbum')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_bn', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('quranic', "Qur'anic studies"), ('islamic', 'Islamic studies'), ('general', 'General education'), ('cocurricular', 'Co-curricular')], max_length=20)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.curriculumgrade')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(content.models.BilingualMixin, models.Model),
        ),
    ]
